### ISSUE TITLE
Make salt.setup idempotent

### ISSUE THREAD

**Issue by stuartornum** [ministryofjustice/bootstrap-salt#30]
Currently if you run salt.setup in the fab task it'll just reinstall everything - which is potentially (not sure if) dangerous - so we should make this a wee bit smarter to check if salt is already setup correctly

**Comment by ashb** [comment]
[[citation needed]]

Are you on the latest version of boostrap-salt?

Doesn't it actually reinstall everything or does it just run the bootstrap-salt.sh script on the master?
